services:
  api:
    build: ./backend
    container_name: afs-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./backend/app:/app/app
      - ./artifacts:/app/artifacts
    environment:
      - DATA_DIR=/app/data/seed
      - ARTIFACTS_DIR=/app/artifacts
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - afs-network

  web:
    build: ./frontend
    container_name: afs-web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:8000/api/v1
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./frontend/src:/web/src
      - /web/node_modules
    restart: unless-stopped
    networks:
      - afs-network

networks:
  afs-network:
    driver: bridge
