title: Attribute Forecasting System
description: ML-powered retail demand forecasting at attribute level with FastAPI backend and React dashboard
theme: jekyll-theme-cayman
show_downloads: true
github:
  repository_url: https://github.com/Julian-Coral/attribute-forecasting-system
  owner_name: Julian-Coral
